# CMake generated Testfile for 
# Source directory: /home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src
# Build directory: /home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[demangle]=] "/home/fedor/CLionProjects/cpp-advanced-hse/demangle_unittest")
set_tests_properties([=[demangle]=] PROPERTIES  DISABLED "ON" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;587;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[logging]=] "/home/fedor/CLionProjects/cpp-advanced-hse/logging_unittest")
set_tests_properties([=[logging]=] PROPERTIES  PASS_REGULAR_EXPRESSION ".*
PASS
.*" SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;616;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[signalhandler]=] "/home/fedor/CLionProjects/cpp-advanced-hse/signalhandler_unittest")
set_tests_properties([=[signalhandler]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;634;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[stacktrace]=] "/home/fedor/CLionProjects/cpp-advanced-hse/stacktrace_unittest")
set_tests_properties([=[stacktrace]=] PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;638;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[stl_logging]=] "/home/fedor/CLionProjects/cpp-advanced-hse/stl_logging_unittest")
set_tests_properties([=[stl_logging]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;642;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[symbolize]=] "/home/fedor/CLionProjects/cpp-advanced-hse/symbolize_unittest")
set_tests_properties([=[symbolize]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: streq\\(\"nonstatic_func\"\\, TrySymbolize\\(\\(void \\*\\)\\(&nonstatic_func\\)\\)\\)" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;645;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cmake_package_config_init]=] "/usr/bin/cmake" "-DTEST_BINARY_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/test_package_config" "-DINITIAL_CACHE=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/test_package_config/glog_package_config_initial_cache.cmake" "-DCACHEVARS=set (BUILD_EXAMPLES ON CACHE BOOL \"Build examples\")
set (BUILD_SHARED_LIBS OFF CACHE BOOL \"Build shared libraries\")
set (BUILD_TESTING ON CACHE BOOL \"Build the testing tree.\")
set (CMAKE_ADDR2LINE \"/usr/bin/addr2line\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"/usr/bin/ar\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"/usr/bin/ar\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_BUILD_TYPE \"TSAN\" CACHE STRING \"Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...\")
set (CMAKE_COLOR_MAKEFILE ON CACHE BOOL \"Enable/Disable color output during build.\")
set (CMAKE_CXX_COMPILER \"/usr/bin/c++\" CACHE FILEPATH \"CXX compiler\")
set (CMAKE_CXX_COMPILER \"/usr/bin/c++\" CACHE FILEPATH \"CXX compiler\")
set (CMAKE_CXX_COMPILER_AR \"/usr/bin/gcc-ar-15\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_COMPILER_AR \"/usr/bin/gcc-ar-15\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-15\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-15\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_FLAGS_ASAN \"-g -fsanitize=address,undefined -fno-sanitize-recover=all\" CACHE STRING \"Compiler flags in asan build\")
set (CMAKE_CXX_FLAGS_DEBUG \"-g\" CACHE STRING \"Flags used by the CXX compiler during DEBUG builds.\")
set (CMAKE_CXX_FLAGS_MINSIZEREL \"-Os -DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during MINSIZEREL builds.\")
set (CMAKE_CXX_FLAGS_MSAN \"-g -fsanitize=memory -fsanitize-recover=all\" CACHE STRING \"Compiler flags in msan build\")
set (CMAKE_CXX_FLAGS_RELEASE \"-O3 -DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELEASE builds.\")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO \"-O2 -g -DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELWITHDEBINFO builds.\")
set (CMAKE_CXX_FLAGS_TSAN \"-g -fsanitize=thread -fno-sanitize-recover=all\" CACHE STRING \"Compiler flags in tsan build\")
set (CMAKE_C_COMPILER \"/usr/bin/cc\" CACHE FILEPATH \"C compiler\")
set (CMAKE_C_COMPILER \"/usr/bin/cc\" CACHE FILEPATH \"C compiler\")
set (CMAKE_C_COMPILER_AR \"/usr/bin/gcc-ar-15\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_COMPILER_AR \"/usr/bin/gcc-ar-15\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-15\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-15\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_FLAGS_DEBUG \"-g\" CACHE STRING \"Flags used by the C compiler during DEBUG builds.\")
set (CMAKE_C_FLAGS_MINSIZEREL \"-Os -DNDEBUG\" CACHE STRING \"Flags used by the C compiler during MINSIZEREL builds.\")
set (CMAKE_C_FLAGS_RELEASE \"-O3 -DNDEBUG\" CACHE STRING \"Flags used by the C compiler during RELEASE builds.\")
set (CMAKE_C_FLAGS_RELWITHDEBINFO \"-O2 -g -DNDEBUG\" CACHE STRING \"Flags used by the C compiler during RELWITHDEBINFO builds.\")
set (CMAKE_DLLTOOL \"CMAKE_DLLTOOL-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_INSTALL_BINDIR \"bin\" CACHE PATH \"User executables (bin)\")
set (CMAKE_INSTALL_DATAROOTDIR \"share\" CACHE PATH \"Read-only architecture-independent data root (share)\")
set (CMAKE_INSTALL_INCLUDEDIR \"include\" CACHE PATH \"C header files (include)\")
set (CMAKE_INSTALL_LIBDIR \"lib\" CACHE PATH \"Object code libraries (lib)\")
set (CMAKE_INSTALL_LIBEXECDIR \"libexec\" CACHE PATH \"Program executables (libexec)\")
set (CMAKE_INSTALL_LOCALSTATEDIR \"var\" CACHE PATH \"Modifiable single-machine data (var)\")
set (CMAKE_INSTALL_OLDINCLUDEDIR \"/usr/include\" CACHE PATH \"C header files for non-gcc (/usr/include)\")
set (CMAKE_INSTALL_PREFIX \"/usr/local\" CACHE PATH \"Install path prefix, prepended onto install directories.\")
set (CMAKE_INSTALL_SBINDIR \"sbin\" CACHE PATH \"System admin executables (sbin)\")
set (CMAKE_INSTALL_SHAREDSTATEDIR \"com\" CACHE PATH \"Modifiable architecture-independent data (com)\")
set (CMAKE_INSTALL_SYSCONFDIR \"etc\" CACHE PATH \"Read-only single-machine data (etc)\")
set (CMAKE_LINKER \"/usr/bin/ld\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_LINKER \"/usr/bin/ld\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MAKE_PROGRAM \"/usr/bin/gmake\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_NM \"/usr/bin/nm\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_OBJCOPY \"/usr/bin/objcopy\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_OBJDUMP \"/usr/bin/objdump\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RANLIB \"/usr/bin/ranlib\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RANLIB \"/usr/bin/ranlib\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_READELF \"/usr/bin/readelf\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_SKIP_INSTALL_RPATH NO CACHE BOOL \"If set, runtime paths are not added when installing shared libraries, but are added when building.\")
set (CMAKE_SKIP_RPATH NO CACHE BOOL \"If set, runtime paths are not added when using shared libraries.\")
set (CMAKE_STRIP \"/usr/bin/strip\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_TAPI \"CMAKE_TAPI-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_TAPI \"CMAKE_TAPI-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_VERBOSE_MAKEFILE FALSE CACHE BOOL \"If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.\")
set (COVERAGE_COMMAND \"/usr/bin/gcov\" CACHE FILEPATH \"Path to the coverage program that CTest uses for performing coverage inspection\")
set (COVERAGE_EXTRA_FLAGS \"-l\" CACHE STRING \"Extra command line flags to pass to the coverage tool\")
set (CPACK_BINARY_DEB OFF CACHE BOOL \"Enable to build Debian packages\")
set (CPACK_BINARY_FREEBSD OFF CACHE BOOL \"Enable to build FreeBSD packages\")
set (CPACK_BINARY_IFW OFF CACHE BOOL \"Enable to build IFW packages\")
set (CPACK_BINARY_NSIS OFF CACHE BOOL \"Enable to build NSIS packages\")
set (CPACK_BINARY_RPM OFF CACHE BOOL \"Enable to build RPM packages\")
set (CPACK_BINARY_STGZ ON CACHE BOOL \"Enable to build STGZ packages\")
set (CPACK_BINARY_TBZ2 OFF CACHE BOOL \"Enable to build TBZ2 packages\")
set (CPACK_BINARY_TGZ ON CACHE BOOL \"Enable to build TGZ packages\")
set (CPACK_BINARY_TXZ OFF CACHE BOOL \"Enable to build TXZ packages\")
set (CPACK_BINARY_TZ ON CACHE BOOL \"Enable to build TZ packages\")
set (CPACK_SOURCE_RPM OFF CACHE BOOL \"Enable to build RPM source packages\")
set (CPACK_SOURCE_TBZ2 ON CACHE BOOL \"Enable to build TBZ2 source packages\")
set (CPACK_SOURCE_TGZ ON CACHE BOOL \"Enable to build TGZ source packages\")
set (CPACK_SOURCE_TXZ ON CACHE BOOL \"Enable to build TXZ source packages\")
set (CPACK_SOURCE_TZ ON CACHE BOOL \"Enable to build TZ source packages\")
set (CPACK_SOURCE_ZIP OFF CACHE BOOL \"Enable to build ZIP source packages\")
set (CTEST_SUBMIT_RETRY_COUNT \"3\" CACHE STRING \"How many times to retry timed-out CTest submissions.\")
set (CTEST_SUBMIT_RETRY_DELAY \"5\" CACHE STRING \"How long to wait between timed-out CTest submissions.\")
set (CURL_DIR \"CURL_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for CURL.\")
set (CURL_INCLUDE_DIR \"CURL_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"Path to a file.\")
set (CURL_LIBRARY_DEBUG \"CURL_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (CURL_LIBRARY_RELEASE \"CURL_LIBRARY_RELEASE-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (DART_TESTING_TIMEOUT \"1500\" CACHE STRING \"Maximum time allowed before CTest will kill the test.\")
set (ENABLE_SEMINARS OFF CACHE BOOL \"OFF\")
set (FETCHCONTENT_BASE_DIR \"/home/fedor/CLionProjects/cpp-advanced-hse/_deps\" CACHE PATH \"Directory under which to collect all populated content\")
set (FETCHCONTENT_BASE_DIR \"/home/fedor/CLionProjects/cpp-advanced-hse/_deps\" CACHE PATH \"Directory under which to collect all populated content\")
set (FETCHCONTENT_FULLY_DISCONNECTED OFF CACHE BOOL \"Disables all attempts to download or update content and assumes source dirs already exist\")
set (FETCHCONTENT_QUIET ON CACHE BOOL \"Enables QUIET option for all content population\")
set (FETCHCONTENT_UPDATES_DISCONNECTED OFF CACHE BOOL \"Enables UPDATE_DISCONNECTED behavior for all content population\")
set (FETCHCONTENT_UPDATES_DISCONNECTED_GLOG OFF CACHE BOOL \"Enables UPDATE_DISCONNECTED behavior just for population of Glog\")
set (FFI_INCLUDE_DIRS \"/usr/include/x86_64-linux-gnu\" CACHE PATH \"Path to a file.\")
set (FFI_LIBRARIES \"/usr/lib/x86_64-linux-gnu/libffi.so\" CACHE FILEPATH \"Path to a library.\")
set (FFI_STATIC_LIBRARIES \"/usr/lib/x86_64-linux-gnu/libffi.a\" CACHE FILEPATH \"Path to a library.\")
set (FFTW_INCLUDES \"FFTW_INCLUDES-NOTFOUND\" CACHE PATH \"Path to a file.\")
set (FFTW_LIBRARIES \"FFTW_LIBRARIES-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (GITCOMMAND \"/usr/bin/git\" CACHE FILEPATH \"Path to a program.\")
set (GIT_EXECUTABLE \"/usr/bin/git\" CACHE FILEPATH \"Git command line client\")
set (GRADER OFF CACHE BOOL \"Building on CI\")
set (GTest_DIR \"GTest_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for GTest.\")
set (JPEG_INCLUDE_DIR \"JPEG_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"Path to a file.\")
set (JPEG_LIBRARY_DEBUG \"JPEG_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (JPEG_LIBRARY_RELEASE \"JPEG_LIBRARY_RELEASE-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (LIBXML2_INCLUDE_DIR \"/usr/include/libxml2\" CACHE PATH \"Path to a file.\")
set (LIBXML2_LIBRARY \"/usr/lib/x86_64-linux-gnu/libxml2.so\" CACHE FILEPATH \"Path to a library.\")
set (LIBXML2_XMLLINT_EXECUTABLE \"LIBXML2_XMLLINT_EXECUTABLE-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (LLVM_DIR \"/usr/lib/llvm-19/cmake\" CACHE PATH \"The directory containing a CMake configuration file for LLVM.\")
set (LibEdit_INCLUDE_DIRS \"LibEdit_INCLUDE_DIRS-NOTFOUND\" CACHE PATH \"Path to a file.\")
set (LibEdit_LIBRARIES \"LibEdit_LIBRARIES-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (MAKECOMMAND \"/usr/bin/cmake --build . --config \\\"\${CTEST_CONFIGURATION_TYPE}\\\"\" CACHE STRING \"Command to build the project\")
set (MEMORYCHECK_COMMAND \"/usr/bin/valgrind\" CACHE FILEPATH \"Path to the memory checking command, used for memory error detection.\")
set (PC_FROM_UCONTEXT \"uc_mcontext.gregs[REG_RIP]\" CACHE STRING \"<ucontext.h> ucontext_t PC member\")
set (PKG_CONFIG_EXECUTABLE \"PKG_CONFIG_EXECUTABLE-NOTFOUND\" CACHE FILEPATH \"pkg-config executable\")
set (PNG_LIBRARY_DEBUG \"PNG_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (PNG_LIBRARY_RELEASE \"PNG_LIBRARY_RELEASE-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (PNG_PNG_INCLUDE_DIR \"PNG_PNG_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"Path to a file.\")
set (PRINT_UNSYMBOLIZED_STACK_TRACES OFF CACHE BOOL \"Print file offsets in traces instead of symbolizing\")
set (SITE \"fedor-pc\" CACHE STRING \"Name of the computer/site where compile is being run\")
set (TEST_SOLUTION OFF CACHE BOOL \"Build solution\")
set (Unwind_INCLUDE_DIR \"Unwind_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"unwind include directory\")
set (Unwind_LIBRARY \"Unwind_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library\")
set (WITH_FUZZING \"none\" CACHE STRING \"Fuzzing engine\")
set (WITH_GMOCK ON CACHE BOOL \"Use Google Mock\")
set (WITH_GTEST ON CACHE BOOL \"Use Google Test\")
set (WITH_PKGCONFIG OFF CACHE BOOL \"Enable pkg-config support\")
set (WITH_SYMBOLIZE ON CACHE BOOL \"Enable symbolize module\")
set (WITH_TLS ON CACHE BOOL \"Enable Thread Local Storage (TLS) support\")
set (WITH_UNWIND \"libunwind\" CACHE STRING \"unwind driver\")
set (ZLIB_INCLUDE_DIR \"/usr/include\" CACHE PATH \"Path to a file.\")
set (ZLIB_LIBRARY_DEBUG \"ZLIB_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (ZLIB_LIBRARY_RELEASE \"/usr/lib/x86_64-linux-gnu/libz.so\" CACHE FILEPATH \"Path to a library.\")
set (zstd_INCLUDE_DIR \"zstd_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"Path to a file.\")
set (zstd_LIBRARY \"zstd_LIBRARY-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (zstd_STATIC_LIBRARY \"zstd_STATIC_LIBRARY-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
" "-P" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/cmake/TestInitPackageConfig.cmake")
set_tests_properties([=[cmake_package_config_init]=] PROPERTIES  FIXTURES_SETUP "cmake_package_config" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;672;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cmake_package_config_generate]=] "/usr/bin/cmake" "-DGENERATOR=Unix Makefiles" "-DGENERATOR_PLATFORM=" "-DGENERATOR_TOOLSET=" "-DINITIAL_CACHE=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/test_package_config/glog_package_config_initial_cache.cmake" "-DPACKAGE_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" "-DPATH=/home/fedor/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" "-DSOURCE_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/package_config_unittest/working_config" "-DTEST_BINARY_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/test_package_config/working_config" "-P" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/cmake/TestPackageConfig.cmake")
set_tests_properties([=[cmake_package_config_generate]=] PROPERTIES  FIXTURES_REQUIRED "cmake_package_config" FIXTURES_SETUP "cmake_package_config_working" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;679;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cmake_package_config_build]=] "/usr/bin/cmake" "--build" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/test_package_config/working_config" "--config" "TSAN")
set_tests_properties([=[cmake_package_config_build]=] PROPERTIES  FIXTURES_REQUIRED "cmake_package_config;cmake_package_config_working" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;691;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cmake_package_config_cleanup]=] "/usr/bin/cmake" "-E" "remove_directory" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/test_package_config")
set_tests_properties([=[cmake_package_config_cleanup]=] PROPERTIES  FIXTURES_CLEANUP "cmake_package_config" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;696;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cleanup_init]=] "/usr/bin/cmake" "-E" "make_directory" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/cleanup_tests")
set_tests_properties([=[cleanup_init]=] PROPERTIES  FIXTURES_SETUP "logcleanuptest" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;734;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cleanup_logdir]=] "/usr/bin/cmake" "-E" "remove_directory" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/cleanup_tests")
set_tests_properties([=[cleanup_logdir]=] PROPERTIES  FIXTURES_CLEANUP "logcleanuptest" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;736;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cleanup_immediately]=] "/usr/bin/cmake" "-DLOGCLEANUP=/home/fedor/CLionProjects/cpp-advanced-hse/cleanup_immediately_unittest" "-DTEST_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/cleanup_tests/" "-P" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/cmake/RunCleanerTest1.cmake")
set_tests_properties([=[cleanup_immediately]=] PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;738;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cleanup_with_absolute_prefix]=] "/usr/bin/cmake" "-DLOGCLEANUP=/home/fedor/CLionProjects/cpp-advanced-hse/cleanup_with_absolute_prefix_unittest" "-DTEST_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/" "-P" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/cmake/RunCleanerTest2.cmake")
set_tests_properties([=[cleanup_with_absolute_prefix]=] PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;745;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[cleanup_with_relative_prefix]=] "/usr/bin/cmake" "-DLOGCLEANUP=/home/fedor/CLionProjects/cpp-advanced-hse/cleanup_with_relative_prefix_unittest" "-DTEST_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/" "-DTEST_SUBDIR=test_subdir/" "-P" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/cmake/RunCleanerTest3.cmake")
set_tests_properties([=[cleanup_with_relative_prefix]=] PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;751;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[striplog0]=] "/home/fedor/CLionProjects/cpp-advanced-hse/striplog0_unittest")
set_tests_properties([=[striplog0]=] PROPERTIES  WILL_FAIL "ON" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;774;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[striplog2]=] "/home/fedor/CLionProjects/cpp-advanced-hse/striplog2_unittest")
set_tests_properties([=[striplog2]=] PROPERTIES  WILL_FAIL "ON" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;782;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[striplog10]=] "/home/fedor/CLionProjects/cpp-advanced-hse/striplog10_unittest")
set_tests_properties([=[striplog10]=] PROPERTIES  WILL_FAIL "ON" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;790;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[log_severity_constants]=] "/usr/bin/ctest" "--build-config" "TSAN" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/log_severity_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/log_severity_constants" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_log_severity_constants" "--build-options" "-DCMAKE_BUILD_TYPE=TSAN" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_GENERATOR_PLATFORM=" "-DCMAKE_GENERATOR_TOOLSET=" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build")
set_tests_properties([=[log_severity_constants]=] PROPERTIES  PASS_REGULAR_EXPRESSION "COMPACT_GOOGLE_LOG_[1-3]" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;799;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[log_severity_conversion]=] "/usr/bin/ctest" "--build-config" "TSAN" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/log_severity_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/log_severity_conversion" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_log_severity_conversion" "--build-options" "-DCMAKE_BUILD_TYPE=TSAN" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_GENERATOR_PLATFORM=" "-DCMAKE_GENERATOR_TOOLSET=" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build")
set_tests_properties([=[log_severity_conversion]=] PROPERTIES  PASS_REGULAR_EXPRESSION "error: invalid conversion from (‘|')int(’|')" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;818;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[includes_logging]=] "/usr/bin/ctest" "--build-config" "TSAN" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/includes_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/includes_logging" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_includes_logging" "--build-options" "-DCMAKE_BUILD_TYPE=TSAN" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_GENERATOR_PLATFORM=" "-DCMAKE_GENERATOR_TOOLSET=" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build")
set_tests_properties([=[includes_logging]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;854;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[includes_vlog_is_on]=] "/usr/bin/ctest" "--build-config" "TSAN" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/includes_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/includes_vlog_is_on" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_includes_vlog_is_on" "--build-options" "-DCMAKE_BUILD_TYPE=TSAN" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_GENERATOR_PLATFORM=" "-DCMAKE_GENERATOR_TOOLSET=" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build")
set_tests_properties([=[includes_vlog_is_on]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;870;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[includes_raw_logging]=] "/usr/bin/ctest" "--build-config" "TSAN" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/includes_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/includes_raw_logging" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_includes_raw_logging" "--build-options" "-DCMAKE_BUILD_TYPE=TSAN" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_GENERATOR_PLATFORM=" "-DCMAKE_GENERATOR_TOOLSET=" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build")
set_tests_properties([=[includes_raw_logging]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;886;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[includes_stl_logging]=] "/usr/bin/ctest" "--build-config" "TSAN" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/includes_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/includes_stl_logging" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_includes_stl_logging" "--build-options" "-DCMAKE_BUILD_TYPE=TSAN" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_GENERATOR_PLATFORM=" "-DCMAKE_GENERATOR_TOOLSET=" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build")
set_tests_properties([=[includes_stl_logging]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;902;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[dcheck_on]=] "/usr/bin/ctest" "--build-config" "Debug" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/dcheck_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/dcheck_on" "--build-generator" "Unix Makefiles" "--build-generator-platform" "" "--build-generator-toolset" "" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_dcheck" "--build-options" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" "--test-command" "glog_dcheck")
set_tests_properties([=[dcheck_on]=] PROPERTIES  DISABLED "1" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" PASS_REGULAR_EXPRESSION "Assert failed: false" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;918;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
add_test([=[dcheck_off]=] "/usr/bin/ctest" "--build-config" "Release" "--build-and-test" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/src/dcheck_unittest" "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build/Tests/dcheck_off" "--build-generator" "Unix Makefiles" "--build-generator-platform" "" "--build-generator-toolset" "" "--build-makeprogram" "/usr/bin/gmake" "--build-target" "glog_dcheck" "--build-options" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-Dglog_DIR=/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" "--test-command" "glog_dcheck")
set_tests_properties([=[dcheck_off]=] PROPERTIES  DISABLED "1" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-build" PASS_REGULAR_EXPRESSION "" _BACKTRACE_TRIPLES "/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;940;add_test;/home/fedor/CLionProjects/cpp-advanced-hse/glog/glog-src/CMakeLists.txt;0;")
